name: pypopart
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - networkx
  - biopython
  - plotly
  - dash
  - dash-bootstrap-components
  - numba
  - scikit-learn
  - pytest
  - pytest-cov
  - pytest-benchmark
  - mypy
  - ruff
  - sphinx
  - sphinx_rtd_theme
  - ipython
  - jupyter
  - notebook